FROM golang:latest as build-env

WORKDIR /go/src/Oceanus
ADD . /go/src/Oceanus

RUN go get -d -v ./...
RUN env GOOS=linux GOARCH=arm go build -o /go/bin/Oceanus

FROM gcr.io/distroless/base
COPY --from=build-env /go/bin/Oceanus /
CMD ["/Oceanus"]
