apiVersion: apps/v1
kind: Deployment
metadata:
  name: oceanus
  namespace: oceanus
  labels:
    app.kubernetes.io/name: oceanus
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oceanus
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oceanus
    spec:
      containers:
      - name: runner
        image: setkeh/oceanus:latest
        ports:
        - containerPort: 1324
        env:
        - name: BUCKET_ACCESS_KEY
          valueFrom:
           secretKeyRef:
             name: oceanus-secrets
             key: BUCKET_ACCESS_KEY
        - name: BUCKET_ENDPOINT
          valueFrom:
           secretKeyRef:
             name: oceanus-secrets
             key: BUCKET_ENDPOINT
        - name: BUCKET_LOCATION
          valueFrom:
           secretKeyRef:
             name: oceanus-secrets
             key: BUCKET_LOCATION
        - name: BUCKET_NAME
          valueFrom:
           secretKeyRef:
             name: oceanus-secrets
             key: BUCKET_NAME
        - name: BUCKET_SECRET_KEY
          valueFrom:
           secretKeyRef:
             name: oceanus-secrets
             key: BUCKET_SECRET_KEY
        - name: DB_CONNECTION_STRING
          valueFrom:
           secretKeyRef:
             name: oceanus-secrets
             key: DB_CONNECTION_STRING
